### Numpy

In [ ]:
# array, matrices, random numbers 

In [10]:
import numpy as np

In [12]:
np.array([2,3,54,6,57])

array([ 2,  3, 54,  6, 57])

In [13]:
a = [435765,7,78,9769,89]

In [15]:
b = np.array(a)
b

array([435765,      7,     78,   9769,     89])

In [16]:
list(b)

[435765, 7, 78, 9769, 89]

In [17]:
type(b)

numpy.ndarray

In [18]:
b

array([435765,      7,     78,   9769,     89])

In [19]:
b.shape

(5,)

In [20]:
b.size

5

In [21]:
len(b)

5

In [22]:
d=[[1,2,3], [4,5,6]]
d

[[1, 2, 3], [4, 5, 6]]

In [25]:
e = np.array(d)
e

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
d[0][1]

2

In [26]:
e[0,1]

2

In [27]:
e.shape

(2, 3)

In [28]:
e.size

6

In [30]:
d

[[1, 2, 3], [4, 5, 6]]

In [32]:
len(d)

2

In [34]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
len(e)

2

In [35]:
e.size

6