In [5]:
import numpy as np

In [23]:
np.random.randint(1, 8)

3

In [24]:
np.random.randint(1, 8)

6

In [25]:
np.random.randint(1, 8)

5

In [26]:
np.random.randint(1, 8)

6

In [27]:
np.random.randint(1, 7)

4

In [28]:
np.random.randint(1, 7)

2

In [30]:
np.random.randint(4,7)

6

In [31]:
np.random.randint(4,99, 3)

array([13,  9, 71])

In [32]:
np.random.randint(4,99, 7)

array([43, 57,  6, 89, 28,  9, 94])

In [33]:
np.random.randint(4,99, (4,4))

array([[45, 72, 84, 25],
       [72, 13, 50, 19],
       [38, 48, 17, 27],
       [94, 72, 47, 20]])

In [34]:
np.random.randint(4,99, (4,10))

array([[11, 98, 51, 80, 49, 56, 27, 52, 90, 88],
       [45, 69, 94, 98, 28, 24, 79, 96, 40, 61],
       [56, 72, 42,  5, 61, 47, 58, 61, 22, 37],
       [87,  4,  8, 53, 72, 95, 36, 75, 80, 93]])

In [35]:
np.random.randint(-40,99, (4,10))

array([[ 91,  36,   3,  95,  23, -35,  57,  47, -13,  73],
       [-24,  10, -39, -31,  94,  58,  80,  57,  18,  73],
       [ -1,  67,  58,   3, -15,  25,   0, -33,  32,  21],
       [ 31,  65,  -3,  64, -12,  67, -20,  35,  -8, -24]])