In [2]:
import numpy

In [3]:
l = [12,32,56,True, 'dwqeer']

In [4]:
np.array(l)

array(['12', '32', '56', 'True', 'dwqeer'], dtype='<U11')

In [5]:
'True' == True

False

In [6]:
np.array([2,3,5, 6.7])

array([2. , 3. , 5. , 6.7])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones((4,4), dtype = 'int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros((4,4), dtype = 'int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
np.zeros(4, dtype = 'int')

array([0, 0, 0, 0])

In [17]:
np.full(3, fill_value = 2)

array([2, 2, 2])

In [18]:
np.full(4, fill_value = 0)

array([0, 0, 0, 0])

In [19]:
np.full((4,6), fill_value = 10)

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [20]:
np.random.randint(4,200, (5,6))

array([[105, 189,   5, 119, 114, 162],
       [175,  98, 141, 185, 155,  85],
       [ 98,  28,  68,  35, 198,  20],
       [158, 173,  27, 102,  48,  75],
       [132, 113,  26,  13,  45, 145]])

In [22]:
np.random.randint(4,200)

12

In [32]:
np.random.seed(0)
np.random.randint(4,200)

176

In [27]:
np.random.randint(4,200)

51

In [33]:
np.random.randint(4,200)

51

In [34]:
np.random.randint(4,200)

121