In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,34], [4,56,7]])
x

array([[ 1,  2, 34],
       [ 4, 56,  7]])

In [3]:
x.shape

(2, 3)

In [4]:
x.ndim

2

In [6]:
y = np.array([[[1,2,34], [4,56,7]], [[3,4,4], [5,6,7]]])
y

array([[[ 1,  2, 34],
        [ 4, 56,  7]],

       [[ 3,  4,  4],
        [ 5,  6,  7]]])

In [7]:
y.shape

(2, 2, 3)

In [13]:
x = np.array([[[1,2,3], [4,5,6]]])
x

array([[[1, 2, 3],
        [4, 5, 6]]])

In [14]:
x.shape

(1, 2, 3)

In [16]:
a = np.array([[[1,2,3], [4,5,6]], [2,4,5]])
a

<ipython-input-16-30739b530b7d>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a = np.array([[[1,2,3], [4,5,6]], [2,4,5]])


array([list([[1, 2, 3], [4, 5, 6]]), list([2, 4, 5])], dtype=object)

In [17]:
a[0]

[[1, 2, 3], [4, 5, 6]]

In [18]:
a[1]

[2, 4, 5]

In [20]:
import pandas as pd
pd.DataFrame(a)

0
0  [[1, 2, 3], [4, 5, 6]]
1               [2, 4, 5]

In [24]:
pd.DataFrame(np.array([[[1,2,3], [4,5,6]], [[2,4,5], [5,6,7]]]))

ValueError: Must pass 2-d input

In [25]:
pd.DataFrame(np.array([[1,2,3], [4,5,6], [2,4,5], [5,6,7]]))

0  1  2
0  1  2  3
1  4  5  6
2  2  4  5
3  5  6  7

In [26]:
d = np.arange(1,10)
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
d_ = d.reshape(3,3)
d_

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
d_.shape

(3, 3)

In [30]:
d.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
d.reshape(1,9).shape

(1, 9)

In [32]:
d.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
# 10 - 2x5, 5x2, 1x10, 10x1

In [34]:
x = np.arange(1,19)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [35]:
x.reshape(3,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [36]:
x.reshape(9,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [37]:
x.reshape(2,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])