In [17]:
import numpy as np

In [18]:
a = np.arange(1,5)
b = np.arange(11,15)

In [19]:
a

array([1, 2, 3, 4])

In [20]:
b

array([11, 12, 13, 14])

In [21]:
a+b

array([12, 14, 16, 18])

In [22]:
b - a

array([10, 10, 10, 10])

In [23]:
a*b

array([11, 24, 39, 56])

In [24]:
a/b

array([0.09090909, 0.16666667, 0.23076923, 0.28571429])

In [25]:
b/a

array([11.        ,  6.        ,  4.33333333,  3.5       ])

In [26]:
c = np.array([list(range(1,7)), list(range(11,17))])
c

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [27]:
d = np.array([list(range(111,117)), list(range(111,117))])
d

array([[111, 112, 113, 114, 115, 116],
       [111, 112, 113, 114, 115, 116]])

In [28]:
c+d

array([[112, 114, 116, 118, 120, 122],
       [122, 124, 126, 128, 130, 132]])

In [29]:
c-d

array([[-110, -110, -110, -110, -110, -110],
       [-100, -100, -100, -100, -100, -100]])

In [30]:
c/d

array([[0.00900901, 0.01785714, 0.02654867, 0.03508772, 0.04347826,
        0.05172414],
       [0.0990991 , 0.10714286, 0.11504425, 0.12280702, 0.13043478,
        0.13793103]])

In [31]:
c*d

array([[ 111,  224,  339,  456,  575,  696],
       [1221, 1344, 1469, 1596, 1725, 1856]])

In [32]:
e = np.array([list(range(111,117)), list(range(110,117))])
e

<ipython-input-32-dce58f2442e9>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  e = np.array([list(range(111,117)), list(range(110,117))])


array([list([111, 112, 113, 114, 115, 116]),
       list([110, 111, 112, 113, 114, 115, 116])], dtype=object)

In [33]:
d+e

ValueError: operands could not be broadcast together with shapes (2,6) (2,) 

In [34]:
a

array([1, 2, 3, 4])

In [35]:
b

array([11, 12, 13, 14])

In [36]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [37]:
d

array([[111, 112, 113, 114, 115, 116],
       [111, 112, 113, 114, 115, 116]])

In [38]:
c*d

array([[ 111,  224,  339,  456,  575,  696],
       [1221, 1344, 1469, 1596, 1725, 1856]])

In [39]:
c.dot(d)

ValueError: shapes (2,6) and (2,6) not aligned: 6 (dim 1) != 2 (dim 0)

In [40]:
c.dot(d.reshape(6,2))

array([[2381, 2402],
       [9161, 9242]])

In [41]:
f = np.array([list(range(1,5)), list(range(6,10))])
f

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [45]:
g = np.array([list(range(1,5)), list(range(11,15)), list(range(21,25))])
g

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24]])

In [46]:
f*g

ValueError: operands could not be broadcast together with shapes (2,4) (3,4) 

In [47]:
f.dot(g.reshape(4,3))

array([[136, 158, 186],
       [336, 408, 486]])

In [48]:
f.dot(g.reshape(4,3)).shape

(2, 3)

In [49]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [50]:
d

array([[111, 112, 113, 114, 115, 116],
       [111, 112, 113, 114, 115, 116]])

In [53]:
np.concatenate([c,d]) # row wise

array([[  1,   2,   3,   4,   5,   6],
       [ 11,  12,  13,  14,  15,  16],
       [111, 112, 113, 114, 115, 116],
       [111, 112, 113, 114, 115, 116]])

In [52]:
np.concatenate([c,d], axis = 1) # column wise

array([[  1,   2,   3,   4,   5,   6, 111, 112, 113, 114, 115, 116],
       [ 11,  12,  13,  14,  15,  16, 111, 112, 113, 114, 115, 116]])

In [57]:
np.concatenate([c,d], axis = 1).ndim

2

In [54]:
np.stack([c,d])

array([[[  1,   2,   3,   4,   5,   6],
        [ 11,  12,  13,  14,  15,  16]],

       [[111, 112, 113, 114, 115, 116],
        [111, 112, 113, 114, 115, 116]]])

In [55]:
np.stack([c,d]).ndim

3

In [56]:
np.stack([c,d]).shape

(2, 2, 6)

In [58]:
np.hstack([c,d])

array([[  1,   2,   3,   4,   5,   6, 111, 112, 113, 114, 115, 116],
       [ 11,  12,  13,  14,  15,  16, 111, 112, 113, 114, 115, 116]])

In [59]:
np.vstack([c,d])

array([[  1,   2,   3,   4,   5,   6],
       [ 11,  12,  13,  14,  15,  16],
       [111, 112, 113, 114, 115, 116],
       [111, 112, 113, 114, 115, 116]])